testing

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -32,6 +32,13 @@ jobs:
       - name: Build Docker Image
         run: docker build -t my-custom-buildozer .
 
+      - name: Check Buildozer Installation
+        run: which buildozer || echo "Buildozer not found"
+
+
+      - name: Fix Buildozer Permissions
+        run: sudo chmod -R 777 .buildozer
+
       #- name: Create .buildozer directory
        # run: mkdir -p $PWD/.buildozer && chmod -R 777 $PWD/.buildozer
         
@@ -54,6 +61,8 @@ jobs:
       - name: Check Buildozer Output
         run: ls -R .buildozer || echo ".buildozer directory not found"
 
+      - name: Print Buildozer Logs
+        run: cat .buildozer/android/platform/build.log || echo "No build log found"
           
       #- name: Check APK location
        # run: find . -name "*.apk" || echo "No APKs found"
